name: dvm

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install dependency
      run: sudo apt-get install kcov

    - name: Run shellcheck
      uses: ludeeus/action-shellcheck@0.1.0

    - name: Run unit test
      run: kcov coverage dvm.sh
      
    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
